name: Sync with upstream repository
on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Add upstream repository
        run: |
          git remote add upstream https://github.com/Aethersailor/Custom_OpenClash_Rules.git
          git fetch upstream

      - name: Create temporary directory for upstream content
        run: mkdir -p upstream_content

      - name: Checkout upstream content
        run: |
          git --work-tree=upstream_content checkout upstream/main -- .
          
      - name: Sync changes (excluding .github and .git)
        run: |
          rsync -av --delete \
            --exclude='.github' \
            --exclude='.git' \
            upstream_content/ .
          
      - name: Clean up
        run: rm -rf upstream_content

      - name: Commit and push changes
        run: |
          git add -A
          git commit -m "Sync with upstream (exclude .github folder)" --allow-empty
          git push origin main
